-- ============================================================
-- Migration: add_activity_plans.sql
-- Creates the activity_plans table for per-day activity plan persistence
-- Idempotent: safe to run multiple times
-- Phase 24: Activity Plan Backend (v1.5 Smart Auto-Logging)
-- ============================================================

-- Create activity_plans table if not exists
CREATE TABLE IF NOT EXISTS activity_plans (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    plan_date DATE NOT NULL,
    plan_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE(user_id, plan_date)
);

-- Index for activity_plans
CREATE INDEX IF NOT EXISTS idx_activity_plans_user_date ON activity_plans(user_id, plan_date);
