-- Migration: add_weight_logs.sql
-- Creates the weight_logs table for weight tracking progress
-- Adds target_weight_kg and target_date columns to profiles
-- Backfills existing user weights from profiles table
-- Idempotent: safe to run multiple times
-- Phase 42: Database Schema & Migration (v1.9 Progress Tracking)
-- Requirements: DB-01, DB-02, DB-03, DB-04

-- DB-01: Create weight_logs table
CREATE TABLE IF NOT EXISTS weight_logs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    weight_kg DECIMAL(5,2) NOT NULL CHECK (weight_kg > 0),
    logged_date DATE NOT NULL,
    source TEXT NOT NULL DEFAULT 'manual',
    notes TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, logged_date),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- DB-02: Add goal columns to profiles table
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS target_weight_kg DECIMAL(5,2) NULL CHECK (target_weight_kg IS NULL OR target_weight_kg > 0);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS target_date DATE NULL;

-- DB-04: Create B-tree index for efficient range queries
CREATE INDEX IF NOT EXISTS idx_weight_logs_user_date_desc ON weight_logs(user_id, logged_date DESC);

-- DB-03: Backfill existing user weights from profiles
INSERT INTO weight_logs (user_id, weight_kg, logged_date, source, notes, created_at)
SELECT p.user_id, p.weight_kg, COALESCE(p.updated_at::DATE, p.created_at::DATE, CURRENT_DATE), 'auto', 'Initial weight from profile setup', NOW()
FROM profiles p
WHERE p.weight_kg IS NOT NULL
AND NOT EXISTS (SELECT 1 FROM weight_logs wl WHERE wl.user_id = p.user_id);
