-- ============================================================
-- Migration: add_meal_plans.sql
-- Creates the meal_plans table (mirrors weekly_plans exactly)
-- Idempotent: safe to run multiple times
-- Phase 18: Database & Prompt Foundation (v1.4 LLM Food Recommendations)
-- ============================================================

-- Create meal_plans table if not exists
CREATE TABLE IF NOT EXISTS meal_plans (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    week_start DATE NOT NULL,
    plan_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE(user_id, week_start)
);

-- Index for meal_plans
CREATE INDEX IF NOT EXISTS idx_meal_plans_user_week ON meal_plans(user_id, week_start);
