-- ============================================================
-- Migration: add_daily_meal_plans.sql
-- Creates the daily_meal_plans table for per-day meal plan persistence
-- Idempotent: safe to run multiple times
-- Phase 26: 3-Day Meal Plan Backend (v1.5 Smart Auto-Logging)
-- ============================================================

CREATE TABLE IF NOT EXISTS daily_meal_plans (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    plan_date DATE NOT NULL,
    plan_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE(user_id, plan_date)
);

CREATE INDEX IF NOT EXISTS idx_daily_meal_plans_user_date ON daily_meal_plans(user_id, plan_date);
