-- Create intensity_level enum if not exists
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'intensity_level') THEN
        CREATE TYPE intensity_level AS ENUM ('light', 'moderate', 'vigorous');
    END IF;
END $$;

-- Create activity_logs table if not exists
CREATE TABLE IF NOT EXISTS activity_logs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    activity_id INT NOT NULL,
    duration_min INT NOT NULL CHECK (duration_min > 0),
    intensity intensity_level NOT NULL,
    calories_burned INT NOT NULL CHECK (calories_burned >= 0),
    logged_date DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE CASCADE
);

-- Index for activity_logs
CREATE INDEX IF NOT EXISTS idx_activity_logs_user_date ON activity_logs(user_id, logged_date);
