-- ============================================================
-- PostgreSQL Schema for Fitness_App
-- Translation of backend/db/init.sql from MySQL to PostgreSQL
-- Idempotent: type and table creation
-- ============================================================

-- ============================================================
-- ENUM Types (D-08: PostgreSQL ENUMs)
-- Created BEFORE any table that references them
-- ============================================================

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'intensity_level') THEN
        CREATE TYPE intensity_level AS ENUM ('light', 'moderate', 'vigorous');
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gender') THEN
        CREATE TYPE gender AS ENUM ('male', 'female', 'other');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'fitness_goal') THEN
        CREATE TYPE fitness_goal AS ENUM ('lose_weight', 'maintain', 'gain_weight');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'activity_level') THEN
        CREATE TYPE activity_level AS ENUM ('sedentary', 'light', 'moderate', 'very_active', 'extra_active');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'food_category') THEN
        CREATE TYPE food_category AS ENUM ('proteins', 'carbs', 'vegetables', 'fruits', 'dairy', 'fats', 'drinks', 'other');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'meal_type') THEN
        CREATE TYPE meal_type AS ENUM ('breakfast', 'lunch', 'dinner', 'snack');
    END IF;
END $$;

-- ============================================================
-- Tables
-- Order: users → profiles → foods → food_logs → activities → user_activity_log
-- ============================================================

-- users table: authentication and consent records
CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,       -- D-09: identity column
    email VARCHAR(255) UNIQUE,
    password_hash VARCHAR(255) NULL,
    google_id VARCHAR(255) UNIQUE NULL,
    pdp_consent BOOLEAN DEFAULT FALSE,                         -- bool column
    pdp_consent_date TIMESTAMPTZ NULL,                         -- D-10: timestamptz
    created_at TIMESTAMPTZ DEFAULT NOW(),                      -- D-10: default now()
    updated_at TIMESTAMPTZ DEFAULT NOW()                       -- D-11: app-managed, no pg trigger
);

-- profiles table: body metrics and fitness goals
CREATE TABLE IF NOT EXISTS profiles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    weight_kg DECIMAL(5,2) NOT NULL CHECK (weight_kg > 0),
    height_cm DECIMAL(5,2) NOT NULL CHECK (height_cm > 0),
    age INT NOT NULL CHECK (age > 0 AND age < 150),
    gender gender NOT NULL,
    fitness_goal fitness_goal NOT NULL,
    activity_level activity_level NULL,
    calorie_rate VARCHAR(10) NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- foods table: seeded + custom food ingredients (D-30)
-- Seeded foods: user_id=NULL, is_custom=FALSE
-- Custom foods: user_id=set, is_custom=TRUE
CREATE TABLE IF NOT EXISTS foods (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NULL,
    name VARCHAR(255) NOT NULL,
    calories_per_100g INT NOT NULL CHECK (calories_per_100g >= 0),
    category food_category NOT NULL,
    is_custom BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- food_logs table: daily food logging (D-33)
-- Supports seeded foods (food_id set) and custom one-off entries (custom_food_name set)
CREATE TABLE IF NOT EXISTS food_logs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    food_id INT NULL,
    custom_food_name VARCHAR(255) NULL,
    calories INT NOT NULL CHECK (calories >= 0),
    portion_grams INT NOT NULL CHECK (portion_grams > 0),
    log_date DATE NOT NULL,
    meal_type meal_type NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (food_id) REFERENCES foods(id) ON DELETE SET NULL
);

-- activities table: exercise recommendations with jsonb metadata
CREATE TABLE IF NOT EXISTS activities (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    duration_min INT NOT NULL CHECK (duration_min > 0),
    estimated_calories INT NOT NULL CHECK (estimated_calories >= 0),
    goal_tags JSONB NOT NULL DEFAULT '[]'::jsonb,              -- D-12: jsonb
    equipment_needed JSONB NOT NULL DEFAULT '[]'::jsonb,       -- D-12: jsonb
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- user_activity_log table: completed activity tracking
CREATE TABLE IF NOT EXISTS user_activity_log (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    activity_id INT NOT NULL,
    completed_date DATE NOT NULL,
    notes TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE CASCADE
);

-- activity_logs table: activity tracking with intensity and calories (replaces user_activity_log)
CREATE TABLE IF NOT EXISTS activity_logs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    activity_id INT NOT NULL,
    duration_min INT NOT NULL CHECK (duration_min > 0),
    intensity intensity_level NOT NULL,
    calories_burned INT NOT NULL CHECK (calories_burned >= 0),
    logged_date DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE CASCADE
);

-- weekly_plans table: LLM-generated weekly activity plans with JSONB plan data
CREATE TABLE IF NOT EXISTS weekly_plans (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    week_start DATE NOT NULL,
    plan_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE(user_id, week_start)
);

-- ============================================================
-- Indexes
-- ============================================================

-- foods table indexes
CREATE INDEX IF NOT EXISTS idx_name ON foods(name);
CREATE INDEX IF NOT EXISTS idx_user_category ON foods(user_id, category);

-- food_logs table indexes
CREATE INDEX IF NOT EXISTS idx_user_date ON food_logs(user_id, log_date);
CREATE INDEX IF NOT EXISTS idx_user_recent ON food_logs(user_id, log_date DESC);

-- user_activity_log table indexes
-- REMOVE AFTER MIGRATION: index on deprecated user_activity_log (kept for backward compat until phase 14 cleanup)
CREATE INDEX IF NOT EXISTS idx_user_date ON user_activity_log(user_id, completed_date);

-- activity_logs table indexes
CREATE INDEX IF NOT EXISTS idx_activity_logs_user_date ON activity_logs(user_id, logged_date);

-- weekly_plans table indexes
CREATE INDEX IF NOT EXISTS idx_weekly_plans_user_week ON weekly_plans(user_id, week_start);
