import { Router } from 'express';

const router = Router();

const apiDocs = {
  api: {
    name: 'Fitness App API',
    description: 'Backend API for Fitness App — BMI, TDEE, food logging, activity tracking, weight progress, and LLM-powered recommendations.',
    version: '1.0.0',
    baseUrl: 'http://localhost:3001',
    format: {
      success: { success: true, data: '...' },
      error: { success: false, error: { message: '...', code: 'UPPER_SNAKE_CASE' } },
    },
    authentication: {
      method: 'httpOnly cookie',
      cookieName: 'token',
      algorithm: 'HS256',
      description: 'Set by POST /api/auth/register and POST /api/auth/login. All endpoints except Health, Auth register/login, and Google OAuth require this cookie.',
    },
    rateLimiting: {
      global: '100 requests per 15 minutes',
      auth: '10 requests per 15 minutes',
      profile: '15 requests per 15 minutes',
      food: '200 requests per 15 minutes',
      activities: '60 requests per 15 minutes',
      progress: '50 requests per 15 minutes',
      weeklyPlans: {
        generate: '50 requests per 1 minute',
        regenerateDay: '30 requests per 1 minute',
        swap: '10 requests per 1 minute',
        toggleComplete: '60 requests per 1 minute',
      },
      activityPlans: '50 requests per 15 minutes',
      dailyMealPlans: '20 requests per 1 minute',
    },
    endpoints: [
      {
        group: 'Health',
        description: 'Server health check',
        basePath: '/api/health',
        items: [
          {
            method: 'GET',
            path: '/api/health',
            auth: false,
            rateLimit: 'global',
            description: 'Health check endpoint',
            response: { status: 'ok', timestamp: 'ISO-8601 string' },
          },
        ],
      },
      {
        group: 'Auth',
        description: 'User registration, login, logout, and session retrieval',
        basePath: '/api/auth',
        items: [
          {
            method: 'POST',
            path: '/api/auth/register',
            auth: false,
            rateLimit: 'auth',
            description: 'Register a new user',
            requestBody: { email: 'string', password: 'string (min 8 chars)', pdpConsent: 'boolean' },
            success: 201,
            response: { user: { id: 'uuid', email: 'string' } },
          },
          {
            method: 'POST',
            path: '/api/auth/login',
            auth: false,
            rateLimit: 'auth',
            description: 'Login with email and password',
            requestBody: { email: 'string', password: 'string' },
            success: 200,
            response: { user: { id: 'uuid', email: 'string' } },
          },
          {
            method: 'POST',
            path: '/api/auth/logout',
            auth: false,
            rateLimit: 'auth',
            description: 'Logout (clear session cookie)',
            response: { message: 'Logged out successfully' },
          },
          {
            method: 'GET',
            path: '/api/auth/me',
            auth: true,
            rateLimit: 'global',
            description: 'Get current authenticated user',
            response: { id: 'uuid', email: 'string', pdp_consent: 'boolean', created_at: 'ISO-8601' },
          },
          {
            method: 'GET',
            path: '/api/auth/google',
            auth: false,
            rateLimit: 'none',
            description: 'Initiate Google OAuth login',
            query: { redirect: 'Frontend URL after login' },
          },
          {
            method: 'GET',
            path: '/api/auth/google/callback',
            auth: false,
            rateLimit: 'none',
            description: 'Google OAuth callback handler — sets JWT cookie and redirects to frontend',
          },
        ],
      },
      {
        group: 'Profile',
        description: 'User profile with BMI, TDEE, and calorie target calculations',
        basePath: '/api/profile',
        auth: 'required',
        items: [
          {
            method: 'POST',
            path: '/api/profile',
            auth: true,
            rateLimit: 'profile',
            description: 'Create profile (first-time setup)',
            requestBody: {
              weightKg: 'number',
              heightCm: 'number',
              age: 'number',
              gender: "('male'|'female')",
              fitnessGoal: "('lose_weight'|'maintain'|'gain_weight')",
              activityLevel: "('sedentary'|'light'|'moderate'|'very_active'|'extra_active')",
              calorieRate: "'slow'|'moderate'|'high'|null",
            },
            success: 201,
            response: { profile: {}, bmi: 'number', bmiCategory: 'string', tdee: 'number', tdeeRange: {}, calorieTarget: 'number|null' },
          },
          {
            method: 'GET',
            path: '/api/profile',
            auth: true,
            rateLimit: 'profile',
            description: 'Get existing profile with calculated metrics',
            response: { profile: {}, bmi: 'number', bmiCategory: 'string', tdee: 'number', tdeeRange: {}, calorieTarget: 'number|null' },
          },
          {
            method: 'PUT',
            path: '/api/profile',
            auth: true,
            rateLimit: 'profile',
            description: 'Update profile and recalculate metrics',
            requestBody: {
              weightKg: 'number',
              heightCm: 'number',
              age: 'number',
              gender: "('male'|'female')",
              fitnessGoal: "('lose_weight'|'maintain'|'gain_weight')",
              activityLevel: "('sedentary'|'light'|'moderate'|'very_active'|'extra_active')",
              calorieRate: "'slow'|'moderate'|'high'|null",
            },
            response: { profile: {}, bmi: 'number', bmiCategory: 'string', tdee: 'number', tdeeRange: {}, calorieTarget: 'number|null' },
          },
        ],
      },
      {
        group: 'Food',
        description: 'Food search, logging, and calorie tracking',
        basePath: '/api/food',
        auth: 'required',
        items: [
          {
            method: 'GET',
            path: '/api/food/search',
            auth: true,
            rateLimit: 'food',
            query: { q: 'string (min 2 chars)' },
            description: 'Search foods by name',
            response: 'array of food objects',
          },
          {
            method: 'POST',
            path: '/api/food',
            auth: true,
            rateLimit: 'food',
            description: 'Create custom food',
            requestBody: { name: 'string', calories_per_100g: 'number', category: 'string|null' },
            success: 201,
            response: 'created food object',
          },
          {
            method: 'POST',
            path: '/api/food/log',
            auth: true,
            rateLimit: 'food',
            description: 'Log a food entry',
            requestBody: {
              foodId: 'uuid|null',
              customFoodName: 'string|null',
              portionGrams: 'number (1-5000)',
              logDate: 'YYYY-MM-DD|null (defaults to today)',
              mealType: "'breakfast'|'lunch'|'dinner'|'snack'",
              calories: 'number (required if customFoodName)',
            },
            success: 201,
            response: 'created log entry',
          },
          {
            method: 'GET',
            path: '/api/food/summary',
            auth: true,
            rateLimit: 'food',
            query: { date: 'YYYY-MM-DD (defaults to today)' },
            description: 'Daily calorie summary with balance',
            response: { date: 'string', totalConsumed: 'number', calorieTarget: 'number|null', remaining: 'number|null', isExtremeDeficit: 'boolean' },
          },
          {
            method: 'GET',
            path: '/api/food/logs',
            auth: true,
            rateLimit: 'food',
            query: { date: 'YYYY-MM-DD (defaults to today)' },
            description: 'Individual log entries for a date',
            response: 'array of log entries',
          },
          {
            method: 'GET',
            path: '/api/food/history',
            auth: true,
            rateLimit: 'food',
            query: { days: 'number (defaults to 7)' },
            description: 'Calorie history for past N days',
            response: 'array of daily totals',
          },
          {
            method: 'GET',
            path: '/api/food/recent',
            auth: true,
            rateLimit: 'food',
            description: 'Recently logged foods for quick-add',
            response: 'array of recent food entries',
          },
        ],
      },
      {
        group: 'Activities',
        description: 'Physical activity database and logging',
        basePath: '/api/activities',
        auth: 'required',
        items: [
          {
            method: 'GET',
            path: '/api/activities',
            auth: true,
            rateLimit: 'activities',
            description: 'Full activity pool filtered by user\'s goal',
            response: { activities: [], total: 'number' },
          },
          {
            method: 'POST',
            path: '/api/activities/log',
            auth: true,
            rateLimit: 'activities',
            description: 'Log a completed activity for today',
            requestBody: { activityId: 'number', durationMin: 'number', intensity: "'light'|'moderate'|'vigorous'", loggedDate: 'YYYY-MM-DD' },
            success: 201,
            response: 'created activity log entry',
          },
          {
            method: 'GET',
            path: '/api/activities/logs',
            auth: true,
            rateLimit: 'activities',
            query: { date: 'YYYY-MM-DD' },
            description: 'Get logged activities for a date',
            response: 'array of activity logs',
          },
          {
            method: 'GET',
            path: '/api/activities/history',
            auth: true,
            rateLimit: 'activities',
            query: { days: 'number', includeEntries: 'boolean' },
            description: 'Get activity history grouped by day',
            response: 'array of daily activity history',
          },
          {
            method: 'DELETE',
            path: '/api/activities/log/:id',
            auth: true,
            rateLimit: 'activities',
            description: 'Delete an activity log entry',
            response: null,
          },
          {
            method: 'GET',
            path: '/api/activities/summary',
            auth: true,
            rateLimit: 'activities',
            query: { date: 'YYYY-MM-DD' },
            description: 'Get daily activity summary and net calories',
            response: { date: 'string', totalActiveMinutes: 'number', totalCaloriesBurned: 'number', totalConsumed: 'number', calorieTarget: 'number', netCalories: 'number', netVsTarget: 'number' },
          },
        ],
      },
      {
        group: 'Progress',
        description: 'Weight history and trend logging',
        basePath: '/api/progress',
        auth: 'required',
        items: [
          {
            method: 'POST',
            path: '/api/progress/weight',
            auth: true,
            rateLimit: 'progress',
            description: 'Log or update weight (upsert)',
            requestBody: { weightKg: 'number', loggedDate: 'YYYY-MM-DD', notes: 'string|null' },
            success: 201,
            response: { entry: {} },
          },
          {
            method: 'GET',
            path: '/api/progress/weight',
            auth: true,
            rateLimit: 'progress',
            query: { limit: 'number' },
            description: 'Get weight logs history sorted descending by date',
            response: { entries: [] },
          },
          {
            method: 'DELETE',
            path: '/api/progress/weight/:id',
            auth: true,
            rateLimit: 'progress',
            description: 'Delete a specific weight entry',
            response: { deleted: true },
          },
        ],
      },
      {
        group: 'Weekly Plans',
        description: 'LLM-generated weekly fitness activity plans',
        basePath: '/api/weekly-plans',
        auth: 'required',
        items: [
          {
            method: 'GET',
            path: '/api/weekly-plans',
            auth: true,
            rateLimit: 'global',
            query: { weekStart: 'YYYY-MM-DD' },
            description: 'Get current weekly plan (checks cache first)',
            response: { plan: {}, fromCache: 'boolean' },
          },
          {
            method: 'POST',
            path: '/api/weekly-plans/generate',
            auth: true,
            rateLimit: 'weeklyPlans.generate',
            requestBody: { weekStart: 'YYYY-MM-DD|null', availableDays: 'number (4-6)' },
            description: 'Generate weekly activity plan (blocking)',
            response: { plan: {}, fromCache: 'boolean' },
          },
          {
            method: 'POST',
            path: '/api/weekly-plans/generate-stream',
            auth: true,
            rateLimit: 'weeklyPlans.generate',
            requestBody: { weekStart: 'YYYY-MM-DD|null', availableDays: 'number (4-6)' },
            description: 'Generate weekly activity plan (Server-Sent Events stream)',
            response: 'text/event-stream of JSON chunks (types: chunk, done, error)',
          },
          {
            method: 'POST',
            path: '/api/weekly-plans/regenerate-day',
            auth: true,
            rateLimit: 'weeklyPlans.regenerateDay',
            requestBody: { weekStart: 'YYYY-MM-DD', dayIndex: 'number (0-6)', availableDays: 'number|null' },
            description: 'Regenerate activities for a single day (blocking)',
            response: { plan: {}, regeneratedDay: 'number', fromCache: 'boolean' },
          },
          {
            method: 'POST',
            path: '/api/weekly-plans/regenerate-day-stream',
            auth: true,
            rateLimit: 'weeklyPlans.regenerateDay',
            requestBody: { weekStart: 'YYYY-MM-DD', dayIndex: 'number (0-6)', availableDays: 'number|null' },
            description: 'Regenerate activities for a single day (Server-Sent Events stream)',
            response: 'text/event-stream of JSON chunks (types: chunk, done, error)',
          },
          {
            method: 'POST',
            path: '/api/weekly-plans/swap',
            auth: true,
            rateLimit: 'weeklyPlans.swap',
            requestBody: { weekStart: 'YYYY-MM-DD', dayIndex: 'number (0-6)', oldActivityName: 'string', intensity: 'string' },
            description: 'Swap a single activity (blocking)',
            response: { plan: {} },
          },
          {
            method: 'POST',
            path: '/api/weekly-plans/swap-stream',
            auth: true,
            rateLimit: 'weeklyPlans.swap',
            requestBody: { weekStart: 'YYYY-MM-DD', dayIndex: 'number (0-6)', activityId: 'number' },
            description: 'Swap a single activity (Server-Sent Events stream)',
            response: 'text/event-stream of JSON chunks (types: chunk, done, error)',
          },
          {
            method: 'POST',
            path: '/api/weekly-plans/toggle-complete',
            auth: true,
            rateLimit: 'weeklyPlans.toggleComplete',
            requestBody: { weekStart: 'YYYY-MM-DD', dayIndex: 'number (0-6)', activityName: 'string' },
            description: 'Toggle completion status of an activity',
            response: { plan: {} },
          },
        ],
      },
      {
        group: 'Daily Meal Plans',
        description: 'LLM-generated daily meal recommendations',
        basePath: '/api/daily-meal-plans',
        auth: 'required',
        items: [
          {
            method: 'GET',
            path: '/api/daily-meal-plans',
            auth: true,
            rateLimit: 'global',
            query: { date: 'YYYY-MM-DD' },
            description: 'Get meal plan for a specific date (checks cache first)',
            response: { plan: {}, fromCache: 'boolean' },
          },
          {
            method: 'POST',
            path: '/api/daily-meal-plans/generate',
            auth: true,
            rateLimit: 'dailyMealPlans',
            requestBody: { date: 'YYYY-MM-DD' },
            description: 'Generate a new daily meal plan (blocking)',
            response: { plan: {}, fromCache: 'boolean' },
          },
          {
            method: 'POST',
            path: '/api/daily-meal-plans/generate-stream',
            auth: true,
            rateLimit: 'dailyMealPlans',
            requestBody: { date: 'YYYY-MM-DD' },
            description: 'Generate daily meal plan (Server-Sent Events stream)',
            response: 'text/event-stream of JSON chunks (types: chunk, done, error)',
          },
          {
            method: 'POST',
            path: '/api/daily-meal-plans/regenerate-category',
            auth: true,
            rateLimit: 'dailyMealPlans',
            requestBody: { date: 'YYYY-MM-DD', mealType: "'breakfast'|'lunch'|'dinner'|'snack'" },
            description: 'Regenerate a specific meal category (blocking)',
            response: { plan: {} },
          },
          {
            method: 'POST',
            path: '/api/daily-meal-plans/regenerate-category-stream',
            auth: true,
            rateLimit: 'dailyMealPlans',
            requestBody: { date: 'YYYY-MM-DD', mealType: "'breakfast'|'lunch'|'dinner'|'snack'" },
            description: 'Regenerate a specific meal category (Server-Sent Events stream)',
            response: 'text/event-stream of JSON chunks (types: chunk, done, error)',
          },
          {
            method: 'POST',
            path: '/api/daily-meal-plans/log',
            auth: true,
            rateLimit: 'global',
            requestBody: { date: 'YYYY-MM-DD', mealType: "'breakfast'|'lunch'|'dinner'|'snack'|null" },
            description: 'Log all or specific meals of the plan to the food log',
            response: { logged: 'number', items: [] },
          },
          {
            method: 'POST',
            path: '/api/daily-meal-plans/toggle-item',
            auth: true,
            rateLimit: 'global',
            requestBody: { date: 'YYYY-MM-DD', mealType: 'string', itemIndex: 'number' },
            description: 'Toggle logged status of a meal item',
            response: { item: {}, logged: 'boolean' },
          },
        ],
      },
      {
        group: 'Activity Plans',
        description: 'Single-day LLM recommendations activity plans',
        basePath: '/api/activity-plans',
        auth: 'required',
        items: [
          {
            method: 'GET',
            path: '/api/activity-plans',
            auth: true,
            rateLimit: 'global',
            query: { date: 'YYYY-MM-DD' },
            description: 'Get daily activity plan',
            response: { plan: {}, fromCache: 'boolean' },
          },
          {
            method: 'POST',
            path: '/api/activity-plans/generate',
            auth: true,
            rateLimit: 'activityPlans',
            requestBody: { date: 'YYYY-MM-DD' },
            description: 'Generate a daily activity recommendation plan',
            response: { plan: {}, fromCache: 'boolean', status: 'string' },
          },
          {
            method: 'POST',
            path: '/api/activity-plans/log',
            auth: true,
            rateLimit: 'global',
            requestBody: { date: 'YYYY-MM-DD', activityIndexes: 'array of numbers' },
            description: 'Batch-log activities from the daily activity plan to logs',
            response: { logged: 'number', activities: [] },
          },
        ],
      },
    ],
  },
};

// GET /api/docs — Return complete API documentation
router.get('/', (req, res) => {
  res.json(apiDocs);
});

export default router;
