import { Router } from 'express';

const router = Router();

const apiDocs = {
  api: {
    name: 'Fitness App API',
    description: 'Backend API for Fitness App — BMI, TDEE, food logging, activity recommendations',
    version: '1.0.0',
    baseUrl: 'http://localhost:3001',
    format: {
      success: { success: true, data: '...' },
      error: { success: false, error: { message: '...', code: 'UPPER_SNAKE_CASE' } },
    },
    authentication: {
      method: 'httpOnly cookie',
      cookieName: 'token',
      algorithm: 'HS256',
      description: 'Set by POST /api/auth/register and POST /api/auth/login. All endpoints except Health, Auth register/login, and Google OAuth require this cookie.',
    },
    rateLimiting: {
      global: '100 requests per 15 minutes',
      auth: '10 requests per 15 minutes',
      profile: '15 requests per 15 minutes',
      food: '200 requests per 15 minutes',
      activities: '60 requests per 15 minutes',
    },
    endpoints: [
      {
        group: 'Health',
        description: 'Server health check',
        basePath: '/api/health',
        items: [
          {
            method: 'GET',
            path: '/api/health',
            auth: false,
            rateLimit: 'global',
            description: 'Health check endpoint',
            response: { status: 'ok', timestamp: 'ISO-8601 string' },
          },
        ],
      },
      {
        group: 'Auth',
        description: 'User registration, login, logout, and profile retrieval',
        basePath: '/api/auth',
        items: [
          {
            method: 'POST',
            path: '/api/auth/register',
            auth: false,
            rateLimit: 'auth',
            description: 'Register a new user',
            requestBody: { email: 'string', password: 'string (min 8 chars)', pdpConsent: 'boolean' },
            success: 201,
            response: { user: { id: 'uuid', email: 'string' } },
          },
          {
            method: 'POST',
            path: '/api/auth/login',
            auth: false,
            rateLimit: 'auth',
            description: 'Login with email and password',
            requestBody: { email: 'string', password: 'string' },
            success: 200,
            response: { user: { id: 'uuid', email: 'string' } },
          },
          {
            method: 'POST',
            path: '/api/auth/logout',
            auth: false,
            rateLimit: 'auth',
            description: 'Logout (clear session cookie)',
            response: { message: 'Logged out successfully' },
          },
          {
            method: 'GET',
            path: '/api/auth/me',
            auth: true,
            rateLimit: 'global',
            description: 'Get current authenticated user',
            response: { user: { id: 'uuid', email: 'string', pdp_consent: 'boolean', created_at: 'ISO-8601' } },
          },
          {
            method: 'GET',
            path: '/api/auth/google',
            auth: false,
            rateLimit: 'none',
            description: 'Initiate Google OAuth login',
            query: { redirect: 'Frontend URL after login' },
          },
          {
            method: 'GET',
            path: '/api/auth/google/callback',
            auth: false,
            rateLimit: 'none',
            description: 'Google OAuth callback handler — sets JWT cookie and redirects to frontend',
          },
        ],
      },
      {
        group: 'Profile',
        description: 'User profile with BMI, TDEE, and calorie target',
        basePath: '/api/profile',
        auth: 'required',
        items: [
          {
            method: 'POST',
            path: '/api/profile',
            auth: true,
            rateLimit: 'profile',
            description: 'Create profile (first-time setup)',
            requestBody: {
              weightKg: 'number',
              heightCm: 'number',
              age: 'number',
              gender: "('male'|'female')",
              fitnessGoal: "('lose_weight'|'maintain'|'gain_weight')",
              activityLevel: "('sedentary'|'light'|'moderate'|'active'|'extra_active')",
              calorieRate: "'slow'|'moderate'|'high'|null",
            },
            success: 201,
            response: { profile: {}, bmi: 'number', bmiCategory: 'string', tdee: 'number', tdeeRange: {}, calorieTarget: 'number|null' },
          },
          {
            method: 'GET',
            path: '/api/profile',
            auth: true,
            rateLimit: 'profile',
            description: 'Get existing profile with calculated metrics',
            response: { profile: {}, bmi: 'number', bmiCategory: 'string', tdee: 'number', tdeeRange: {}, calorieTarget: 'number|null' },
          },
          {
            method: 'PUT',
            path: '/api/profile',
            auth: true,
            rateLimit: 'profile',
            description: 'Update profile',
            requestBody: {
              weightKg: 'number',
              heightCm: 'number',
              age: 'number',
              gender: "('male'|'female')",
              fitnessGoal: "('lose_weight'|'maintain'|'gain_weight')",
              activityLevel: "('sedentary'|'light'|'moderate'|'active'|'extra_active')",
              calorieRate: "'slow'|'moderate'|'high'|null",
            },
            response: { profile: {}, bmi: 'number', bmiCategory: 'string', tdee: 'number', tdeeRange: {}, calorieTarget: 'number|null' },
          },
        ],
      },
      {
        group: 'Food',
        description: 'Food search, logging, and calorie tracking',
        basePath: '/api/food',
        auth: 'required',
        items: [
          {
            method: 'GET',
            path: '/api/food/search',
            auth: true,
            rateLimit: 'food',
            query: { q: 'string (min 2 chars)' },
            description: 'Search foods by name',
            response: 'array of food objects',
          },
          {
            method: 'POST',
            path: '/api/food',
            auth: true,
            rateLimit: 'food',
            description: 'Create custom food',
            requestBody: { name: 'string', calories_per_100g: 'number', category: 'string|null' },
            success: 201,
            response: 'created food object',
          },
          {
            method: 'POST',
            path: '/api/food/log',
            auth: true,
            rateLimit: 'food',
            description: 'Log a food entry',
            requestBody: {
              foodId: 'uuid|null',
              customFoodName: 'string|null',
              portionGrams: 'number (1-5000)',
              logDate: 'YYYY-MM-DD|null (defaults to today)',
              mealType: "'breakfast'|'lunch'|'dinner'|'snack'",
              calories: 'number (required if customFoodName)',
            },
            success: 201,
            response: 'created log entry',
          },
          {
            method: 'GET',
            path: '/api/food/summary',
            auth: true,
            rateLimit: 'food',
            query: { date: 'YYYY-MM-DD (defaults to today)' },
            description: 'Daily calorie summary with balance',
            response: { date: 'string', totalConsumed: 'number', calorieTarget: 'number|null', remaining: 'number|null', isExtremeDeficit: 'boolean' },
          },
          {
            method: 'GET',
            path: '/api/food/logs',
            auth: true,
            rateLimit: 'food',
            query: { date: 'YYYY-MM-DD (defaults to today)' },
            description: 'Individual log entries for a date',
            response: 'array of log entries',
          },
          {
            method: 'GET',
            path: '/api/food/history',
            auth: true,
            rateLimit: 'food',
            query: { days: 'number (defaults to 7)' },
            description: 'Calorie history for past N days',
            response: 'array of daily totals',
          },
          {
            method: 'GET',
            path: '/api/food/recent',
            auth: true,
            rateLimit: 'food',
            description: 'Recently logged foods for quick-add',
            response: 'array of recent food entries',
          },
        ],
      },
      {
        group: 'Activities',
        description: 'Physical activity recommendations and pool',
        basePath: '/api/activities',
        auth: 'required',
        items: [
          {
            method: 'GET',
            path: '/api/activities/recommendations',
            auth: true,
            rateLimit: 'activities',
            description: 'Randomized goal-based activity recommendations',
            response: { activities: [], count: 'number' },
          },
          {
            method: 'GET',
            path: '/api/activities',
            auth: true,
            rateLimit: 'activities',
            description: 'Full activity pool filtered by user\'s goal',
            response: { activities: [], total: 'number' },
          },
        ],
      },
    ],
  },
};

// GET /api/docs — Return complete API documentation
router.get('/', (req, res) => {
  res.json(apiDocs);
});

export default router;
